[package]
name = "logging"
version = "0.3.0"
authors = ["Jonathan Strong <jstrong@legis.io>"]

[dependencies]
zmq = "0.8"
influent = "0.4"
chrono = { version = "0.4", features = ["serde"] }
hyper = "0.10"
termion = "1.4.0"
# pub-sub = "2.0"
slog = "2.0.6"
sloggers = "0.2"
slog-term = "2"
# chashmap = "2"
ordermap = "0.2"
fnv = "1"
uuid = { version = "0.5", features = ["serde", "v4"] }

decimal = { path = "../decimal", version = "2" }

windows = { path = "../windows", version = "0.1" }
money = { path = "../money", version = "0.2" }
pubsub = { path = "../pubsub" }

[features]
no-thrash = []
trace = []
test = []
