[package]
name = "logging"
version = "0.5.1"
authors = ["Jonathan Strong <jonathan.strong@gmail.com>"]
edition = "2018"

[[example]]
name = "zmq-logger"
path = "examples/zmq-logger.rs"
required-features = ["warnings", "zmq"]

[[example]]
name = "hist-interval"
path = "examples/hist-interval.rs"

[dependencies]
zmq = { version = "0.8", optional = true }
influent = "0.4"
chrono = { version = "0.4", features = ["serde"] }
hyper = "0.10"
termion = "1.4.0"
slog = "2.0.6"
slog-term = "2"
ordermap = "0.3"
fnv = "1"
uuid = { version = "0.6", features = ["serde", "v4", "nightly", "const_fn"] }
hdrhistogram = "6"
slog-async = "2"
smallvec = "0.6"
num = "0.1"
dirs = "1"
crossbeam-channel = "0.3"
pretty_toa = "1.0.0"

sloggers = "0.3"
#sloggers = { path = "../sloggers" }

decimal = { path = "../decimal", version = "2" }

#windows = { path = "../windows", version = "0.2" }
money = { path = "../money", version = "0.3" }
pubsub = { path = "../pubsub", optional = true }

[features]
default = ["inlines"]
no-thrash = []
trace = ["slog/release_max_level_trace", "slog/max_level_trace"]
debug = ["slog/release_max_level_debug", "slog/max_level_debug"]
test = []
localhost = []
harrison = []
washington = []
scholes = []
no-influx-buffer = []
disable-short-uuid = []
warnings = []
inlines = []
latency = ["pubsub"]
